/* DO NOT EDIT THIS FILE - it is machine generated */
#ifdef _WIN32
	#include <jni/windows/jni.h>
	#include <jni/windows/jni_md.h>
#else
	#include <jni/linux/jni.h>
	#include <jni/linux/jni_md.h>
#endif

/* Header for class cn_bubi_Privacy */

#ifndef _Included_cn_bubi_Privacy
#define _Included_cn_bubi_Privacy
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     cn_bubi_Privacy
	* Method:    init
	* Signature: ()J
	*/
	JNIEXPORT jlong JNICALL Java_cn_bubi_Privacy_init
		(JNIEnv *, jclass);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    destroy
	* Signature: (J)V
	*/
	JNIEXPORT void JNICALL Java_cn_bubi_Privacy_destroy
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    createPedersenCommit
	* Signature: (JJLjava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_createPedersenCommit
		(JNIEnv *, jclass, jlong, jlong, jstring);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    createEcdhKey
	* Signature: (JLjava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_createEcdhKey
		(JNIEnv *, jclass, jlong, jstring, jstring);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    createKeyPair
	* Signature: (J)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_createKeyPair
		(JNIEnv *, jclass, jlong);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    getPublicKey
	* Signature: (JLjava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_getPublicKey
		(JNIEnv *, jclass, jlong, jstring);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    bpRangeproofProve
	* Signature: (J[Ljava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_bpRangeproofProve
		(JNIEnv *, jclass, jlong, jstring, jlong);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    bpRangeproofVerify
	* Signature: (J[Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_bpRangeproofVerify
		(JNIEnv *, jclass, jlong, jstring, jstring);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    ecdsaSign
	* Signature: (JLjava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_ecdsaSign
		(JNIEnv *, jclass, jlong, jstring, jstring);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    ecdsaVerify
	* Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_ecdsaVerify
		(JNIEnv *, jclass, jlong, jstring, jstring, jstring);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    excessSign
	* Signature: (J[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_excessSign
		(JNIEnv *, jclass, jlong, jobjectArray, jobjectArray, jstring);

	/*
	* Class:     cn_bubi_Privacy
	* Method:    pedersenTallyVerify
	* Signature: (J[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
	*/
	JNIEXPORT jobjectArray JNICALL Java_cn_bubi_Privacy_pedersenTallyVerify
		(JNIEnv *, jclass, jlong, jobjectArray, jobjectArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
