// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: privacy.proto

package cn.bubi.protobuf;

public final class Privacy {
  private Privacy() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfidentialAssetOrBuilder extends
          // @@protoc_insertion_point(interface_extends:protocol.ConfidentialAsset)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>optional string commit = 2;</code>
     */
    java.lang.String getCommit();
    /**
     * <code>optional string commit = 2;</code>
     */
    com.google.protobuf.ByteString
    getCommitBytes();

    /**
     * <code>optional string range_proof = 3;</code>
     */
    java.lang.String getRangeProof();
    /**
     * <code>optional string range_proof = 3;</code>
     */
    com.google.protobuf.ByteString
    getRangeProofBytes();

    /**
     * <code>optional string encrypt_value = 4;</code>
     */
    java.lang.String getEncryptValue();
    /**
     * <code>optional string encrypt_value = 4;</code>
     */
    com.google.protobuf.ByteString
    getEncryptValueBytes();

    /**
     * <code>optional string from_pubkey = 5;</code>
     */
    java.lang.String getFromPubkey();
    /**
     * <code>optional string from_pubkey = 5;</code>
     */
    com.google.protobuf.ByteString
    getFromPubkeyBytes();

    /**
     * <code>optional string to = 6;</code>
     */
    java.lang.String getTo();
    /**
     * <code>optional string to = 6;</code>
     */
    com.google.protobuf.ByteString
    getToBytes();
  }
  /**
   * Protobuf type {@code protocol.ConfidentialAsset}
   */
  public  static final class ConfidentialAsset extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:protocol.ConfidentialAsset)
          ConfidentialAssetOrBuilder {
    // Use ConfidentialAsset.newBuilder() to construct.
    private ConfidentialAsset(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfidentialAsset() {
      id_ = "";
      commit_ = "";
      rangeProof_ = "";
      encryptValue_ = "";
      fromPubkey_ = "";
      to_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConfidentialAsset(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              commit_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              rangeProof_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              encryptValue_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              fromPubkey_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialAsset_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialAsset_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      cn.bubi.protobuf.Privacy.ConfidentialAsset.class, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
    getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMIT_FIELD_NUMBER = 2;
    private volatile java.lang.Object commit_;
    /**
     * <code>optional string commit = 2;</code>
     */
    public java.lang.String getCommit() {
      java.lang.Object ref = commit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commit_ = s;
        return s;
      }
    }
    /**
     * <code>optional string commit = 2;</code>
     */
    public com.google.protobuf.ByteString
    getCommitBytes() {
      java.lang.Object ref = commit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        commit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RANGE_PROOF_FIELD_NUMBER = 3;
    private volatile java.lang.Object rangeProof_;
    /**
     * <code>optional string range_proof = 3;</code>
     */
    public java.lang.String getRangeProof() {
      java.lang.Object ref = rangeProof_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rangeProof_ = s;
        return s;
      }
    }
    /**
     * <code>optional string range_proof = 3;</code>
     */
    public com.google.protobuf.ByteString
    getRangeProofBytes() {
      java.lang.Object ref = rangeProof_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        rangeProof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCRYPT_VALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object encryptValue_;
    /**
     * <code>optional string encrypt_value = 4;</code>
     */
    public java.lang.String getEncryptValue() {
      java.lang.Object ref = encryptValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encryptValue_ = s;
        return s;
      }
    }
    /**
     * <code>optional string encrypt_value = 4;</code>
     */
    public com.google.protobuf.ByteString
    getEncryptValueBytes() {
      java.lang.Object ref = encryptValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        encryptValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_PUBKEY_FIELD_NUMBER = 5;
    private volatile java.lang.Object fromPubkey_;
    /**
     * <code>optional string from_pubkey = 5;</code>
     */
    public java.lang.String getFromPubkey() {
      java.lang.Object ref = fromPubkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromPubkey_ = s;
        return s;
      }
    }
    /**
     * <code>optional string from_pubkey = 5;</code>
     */
    public com.google.protobuf.ByteString
    getFromPubkeyBytes() {
      java.lang.Object ref = fromPubkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        fromPubkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 6;
    private volatile java.lang.Object to_;
    /**
     * <code>optional string to = 6;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>optional string to = 6;</code>
     */
    public com.google.protobuf.ByteString
    getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCommitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commit_);
      }
      if (!getRangeProofBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, rangeProof_);
      }
      if (!getEncryptValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, encryptValue_);
      }
      if (!getFromPubkeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, fromPubkey_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, to_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCommitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, commit_);
      }
      if (!getRangeProofBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, rangeProof_);
      }
      if (!getEncryptValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, encryptValue_);
      }
      if (!getFromPubkeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, fromPubkey_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, to_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof cn.bubi.protobuf.Privacy.ConfidentialAsset)) {
        return super.equals(obj);
      }
      cn.bubi.protobuf.Privacy.ConfidentialAsset other = (cn.bubi.protobuf.Privacy.ConfidentialAsset) obj;

      boolean result = true;
      result = result && getId()
              .equals(other.getId());
      result = result && getCommit()
              .equals(other.getCommit());
      result = result && getRangeProof()
              .equals(other.getRangeProof());
      result = result && getEncryptValue()
              .equals(other.getEncryptValue());
      result = result && getFromPubkey()
              .equals(other.getFromPubkey());
      result = result && getTo()
              .equals(other.getTo());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCommit().hashCode();
      hash = (37 * hash) + RANGE_PROOF_FIELD_NUMBER;
      hash = (53 * hash) + getRangeProof().hashCode();
      hash = (37 * hash) + ENCRYPT_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptValue().hashCode();
      hash = (37 * hash) + FROM_PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getFromPubkey().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialAsset parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.bubi.protobuf.Privacy.ConfidentialAsset prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ConfidentialAsset}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protocol.ConfidentialAsset)
            cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialAsset_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialAsset_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.bubi.protobuf.Privacy.ConfidentialAsset.class, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder.class);
      }

      // Construct using cn.bubi.protobuf.Privacy.ConfidentialAsset.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        commit_ = "";

        rangeProof_ = "";

        encryptValue_ = "";

        fromPubkey_ = "";

        to_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialAsset_descriptor;
      }

      public cn.bubi.protobuf.Privacy.ConfidentialAsset getDefaultInstanceForType() {
        return cn.bubi.protobuf.Privacy.ConfidentialAsset.getDefaultInstance();
      }

      public cn.bubi.protobuf.Privacy.ConfidentialAsset build() {
        cn.bubi.protobuf.Privacy.ConfidentialAsset result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.bubi.protobuf.Privacy.ConfidentialAsset buildPartial() {
        cn.bubi.protobuf.Privacy.ConfidentialAsset result = new cn.bubi.protobuf.Privacy.ConfidentialAsset(this);
        result.id_ = id_;
        result.commit_ = commit_;
        result.rangeProof_ = rangeProof_;
        result.encryptValue_ = encryptValue_;
        result.fromPubkey_ = fromPubkey_;
        result.to_ = to_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.bubi.protobuf.Privacy.ConfidentialAsset) {
          return mergeFrom((cn.bubi.protobuf.Privacy.ConfidentialAsset)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.bubi.protobuf.Privacy.ConfidentialAsset other) {
        if (other == cn.bubi.protobuf.Privacy.ConfidentialAsset.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getCommit().isEmpty()) {
          commit_ = other.commit_;
          onChanged();
        }
        if (!other.getRangeProof().isEmpty()) {
          rangeProof_ = other.rangeProof_;
          onChanged();
        }
        if (!other.getEncryptValue().isEmpty()) {
          encryptValue_ = other.encryptValue_;
          onChanged();
        }
        if (!other.getFromPubkey().isEmpty()) {
          fromPubkey_ = other.fromPubkey_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        cn.bubi.protobuf.Privacy.ConfidentialAsset parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.bubi.protobuf.Privacy.ConfidentialAsset) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
      getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commit_ = "";
      /**
       * <code>optional string commit = 2;</code>
       */
      public java.lang.String getCommit() {
        java.lang.Object ref = commit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string commit = 2;</code>
       */
      public com.google.protobuf.ByteString
      getCommitBytes() {
        java.lang.Object ref = commit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          commit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string commit = 2;</code>
       */
      public Builder setCommit(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        commit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string commit = 2;</code>
       */
      public Builder clearCommit() {

        commit_ = getDefaultInstance().getCommit();
        onChanged();
        return this;
      }
      /**
       * <code>optional string commit = 2;</code>
       */
      public Builder setCommitBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        commit_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rangeProof_ = "";
      /**
       * <code>optional string range_proof = 3;</code>
       */
      public java.lang.String getRangeProof() {
        java.lang.Object ref = rangeProof_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rangeProof_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string range_proof = 3;</code>
       */
      public com.google.protobuf.ByteString
      getRangeProofBytes() {
        java.lang.Object ref = rangeProof_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          rangeProof_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string range_proof = 3;</code>
       */
      public Builder setRangeProof(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        rangeProof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string range_proof = 3;</code>
       */
      public Builder clearRangeProof() {

        rangeProof_ = getDefaultInstance().getRangeProof();
        onChanged();
        return this;
      }
      /**
       * <code>optional string range_proof = 3;</code>
       */
      public Builder setRangeProofBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        rangeProof_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object encryptValue_ = "";
      /**
       * <code>optional string encrypt_value = 4;</code>
       */
      public java.lang.String getEncryptValue() {
        java.lang.Object ref = encryptValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          encryptValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string encrypt_value = 4;</code>
       */
      public com.google.protobuf.ByteString
      getEncryptValueBytes() {
        java.lang.Object ref = encryptValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          encryptValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string encrypt_value = 4;</code>
       */
      public Builder setEncryptValue(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        encryptValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string encrypt_value = 4;</code>
       */
      public Builder clearEncryptValue() {

        encryptValue_ = getDefaultInstance().getEncryptValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string encrypt_value = 4;</code>
       */
      public Builder setEncryptValueBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        encryptValue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromPubkey_ = "";
      /**
       * <code>optional string from_pubkey = 5;</code>
       */
      public java.lang.String getFromPubkey() {
        java.lang.Object ref = fromPubkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromPubkey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from_pubkey = 5;</code>
       */
      public com.google.protobuf.ByteString
      getFromPubkeyBytes() {
        java.lang.Object ref = fromPubkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          fromPubkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from_pubkey = 5;</code>
       */
      public Builder setFromPubkey(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        fromPubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_pubkey = 5;</code>
       */
      public Builder clearFromPubkey() {

        fromPubkey_ = getDefaultInstance().getFromPubkey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from_pubkey = 5;</code>
       */
      public Builder setFromPubkeyBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        fromPubkey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>optional string to = 6;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to = 6;</code>
       */
      public com.google.protobuf.ByteString
      getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to = 6;</code>
       */
      public Builder setTo(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 6;</code>
       */
      public Builder clearTo() {

        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 6;</code>
       */
      public Builder setToBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        to_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protocol.ConfidentialAsset)
    }

    // @@protoc_insertion_point(class_scope:protocol.ConfidentialAsset)
    private static final cn.bubi.protobuf.Privacy.ConfidentialAsset DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.bubi.protobuf.Privacy.ConfidentialAsset();
    }

    public static cn.bubi.protobuf.Privacy.ConfidentialAsset getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfidentialAsset>
            PARSER = new com.google.protobuf.AbstractParser<ConfidentialAsset>() {
      public ConfidentialAsset parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfidentialAsset(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfidentialAsset> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfidentialAsset> getParserForType() {
      return PARSER;
    }

    public cn.bubi.protobuf.Privacy.ConfidentialAsset getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConfidentialTxOrBuilder extends
          // @@protoc_insertion_point(interface_extends:protocol.ConfidentialTx)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string excess_sig = 1;</code>
     */
    java.lang.String getExcessSig();
    /**
     * <code>optional string excess_sig = 1;</code>
     */
    com.google.protobuf.ByteString
    getExcessSigBytes();

    /**
     * <code>optional string excess_msg = 2;</code>
     */
    java.lang.String getExcessMsg();
    /**
     * <code>optional string excess_msg = 2;</code>
     */
    com.google.protobuf.ByteString
    getExcessMsgBytes();

    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset>
    getInputsList();
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    cn.bubi.protobuf.Privacy.ConfidentialAsset getInputs(int index);
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    int getInputsCount();
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    java.util.List<? extends cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
    getInputsOrBuilderList();
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder getInputsOrBuilder(
            int index);

    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset>
    getOutputsList();
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    cn.bubi.protobuf.Privacy.ConfidentialAsset getOutputs(int index);
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    int getOutputsCount();
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    java.util.List<? extends cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
    getOutputsOrBuilderList();
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder getOutputsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code protocol.ConfidentialTx}
   */
  public  static final class ConfidentialTx extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:protocol.ConfidentialTx)
          ConfidentialTxOrBuilder {
    // Use ConfidentialTx.newBuilder() to construct.
    private ConfidentialTx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfidentialTx() {
      excessSig_ = "";
      excessMsg_ = "";
      inputs_ = java.util.Collections.emptyList();
      outputs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConfidentialTx(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              excessSig_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              excessMsg_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                inputs_ = new java.util.ArrayList<cn.bubi.protobuf.Privacy.ConfidentialAsset>();
                mutable_bitField0_ |= 0x00000004;
              }
              inputs_.add(
                      input.readMessage(cn.bubi.protobuf.Privacy.ConfidentialAsset.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                outputs_ = new java.util.ArrayList<cn.bubi.protobuf.Privacy.ConfidentialAsset>();
                mutable_bitField0_ |= 0x00000008;
              }
              outputs_.add(
                      input.readMessage(cn.bubi.protobuf.Privacy.ConfidentialAsset.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          inputs_ = java.util.Collections.unmodifiableList(inputs_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          outputs_ = java.util.Collections.unmodifiableList(outputs_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialTx_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialTx_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      cn.bubi.protobuf.Privacy.ConfidentialTx.class, cn.bubi.protobuf.Privacy.ConfidentialTx.Builder.class);
    }

    private int bitField0_;
    public static final int EXCESS_SIG_FIELD_NUMBER = 1;
    private volatile java.lang.Object excessSig_;
    /**
     * <code>optional string excess_sig = 1;</code>
     */
    public java.lang.String getExcessSig() {
      java.lang.Object ref = excessSig_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excessSig_ = s;
        return s;
      }
    }
    /**
     * <code>optional string excess_sig = 1;</code>
     */
    public com.google.protobuf.ByteString
    getExcessSigBytes() {
      java.lang.Object ref = excessSig_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        excessSig_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCESS_MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object excessMsg_;
    /**
     * <code>optional string excess_msg = 2;</code>
     */
    public java.lang.String getExcessMsg() {
      java.lang.Object ref = excessMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        excessMsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string excess_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
    getExcessMsgBytes() {
      java.lang.Object ref = excessMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        excessMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUTS_FIELD_NUMBER = 3;
    private java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> inputs_;
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    public java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> getInputsList() {
      return inputs_;
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    public java.util.List<? extends cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
    getInputsOrBuilderList() {
      return inputs_;
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    public int getInputsCount() {
      return inputs_.size();
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    public cn.bubi.protobuf.Privacy.ConfidentialAsset getInputs(int index) {
      return inputs_.get(index);
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
     */
    public cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder getInputsOrBuilder(
            int index) {
      return inputs_.get(index);
    }

    public static final int OUTPUTS_FIELD_NUMBER = 4;
    private java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> outputs_;
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    public java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> getOutputsList() {
      return outputs_;
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    public java.util.List<? extends cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
    getOutputsOrBuilderList() {
      return outputs_;
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    public int getOutputsCount() {
      return outputs_.size();
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    public cn.bubi.protobuf.Privacy.ConfidentialAsset getOutputs(int index) {
      return outputs_.get(index);
    }
    /**
     * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
     */
    public cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder getOutputsOrBuilder(
            int index) {
      return outputs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getExcessSigBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, excessSig_);
      }
      if (!getExcessMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, excessMsg_);
      }
      for (int i = 0; i < inputs_.size(); i++) {
        output.writeMessage(3, inputs_.get(i));
      }
      for (int i = 0; i < outputs_.size(); i++) {
        output.writeMessage(4, outputs_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getExcessSigBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, excessSig_);
      }
      if (!getExcessMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, excessMsg_);
      }
      for (int i = 0; i < inputs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(3, inputs_.get(i));
      }
      for (int i = 0; i < outputs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(4, outputs_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof cn.bubi.protobuf.Privacy.ConfidentialTx)) {
        return super.equals(obj);
      }
      cn.bubi.protobuf.Privacy.ConfidentialTx other = (cn.bubi.protobuf.Privacy.ConfidentialTx) obj;

      boolean result = true;
      result = result && getExcessSig()
              .equals(other.getExcessSig());
      result = result && getExcessMsg()
              .equals(other.getExcessMsg());
      result = result && getInputsList()
              .equals(other.getInputsList());
      result = result && getOutputsList()
              .equals(other.getOutputsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + EXCESS_SIG_FIELD_NUMBER;
      hash = (53 * hash) + getExcessSig().hashCode();
      hash = (37 * hash) + EXCESS_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getExcessMsg().hashCode();
      if (getInputsCount() > 0) {
        hash = (37 * hash) + INPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getInputsList().hashCode();
      }
      if (getOutputsCount() > 0) {
        hash = (37 * hash) + OUTPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getOutputsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static cn.bubi.protobuf.Privacy.ConfidentialTx parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.bubi.protobuf.Privacy.ConfidentialTx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ConfidentialTx}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:protocol.ConfidentialTx)
            cn.bubi.protobuf.Privacy.ConfidentialTxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialTx_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialTx_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.bubi.protobuf.Privacy.ConfidentialTx.class, cn.bubi.protobuf.Privacy.ConfidentialTx.Builder.class);
      }

      // Construct using cn.bubi.protobuf.Privacy.ConfidentialTx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInputsFieldBuilder();
          getOutputsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        excessSig_ = "";

        excessMsg_ = "";

        if (inputsBuilder_ == null) {
          inputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          inputsBuilder_.clear();
        }
        if (outputsBuilder_ == null) {
          outputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          outputsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return cn.bubi.protobuf.Privacy.internal_static_protocol_ConfidentialTx_descriptor;
      }

      public cn.bubi.protobuf.Privacy.ConfidentialTx getDefaultInstanceForType() {
        return cn.bubi.protobuf.Privacy.ConfidentialTx.getDefaultInstance();
      }

      public cn.bubi.protobuf.Privacy.ConfidentialTx build() {
        cn.bubi.protobuf.Privacy.ConfidentialTx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.bubi.protobuf.Privacy.ConfidentialTx buildPartial() {
        cn.bubi.protobuf.Privacy.ConfidentialTx result = new cn.bubi.protobuf.Privacy.ConfidentialTx(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.excessSig_ = excessSig_;
        result.excessMsg_ = excessMsg_;
        if (inputsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            inputs_ = java.util.Collections.unmodifiableList(inputs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.inputs_ = inputs_;
        } else {
          result.inputs_ = inputsBuilder_.build();
        }
        if (outputsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            outputs_ = java.util.Collections.unmodifiableList(outputs_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.outputs_ = outputs_;
        } else {
          result.outputs_ = outputsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.bubi.protobuf.Privacy.ConfidentialTx) {
          return mergeFrom((cn.bubi.protobuf.Privacy.ConfidentialTx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.bubi.protobuf.Privacy.ConfidentialTx other) {
        if (other == cn.bubi.protobuf.Privacy.ConfidentialTx.getDefaultInstance()) return this;
        if (!other.getExcessSig().isEmpty()) {
          excessSig_ = other.excessSig_;
          onChanged();
        }
        if (!other.getExcessMsg().isEmpty()) {
          excessMsg_ = other.excessMsg_;
          onChanged();
        }
        if (inputsBuilder_ == null) {
          if (!other.inputs_.isEmpty()) {
            if (inputs_.isEmpty()) {
              inputs_ = other.inputs_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInputsIsMutable();
              inputs_.addAll(other.inputs_);
            }
            onChanged();
          }
        } else {
          if (!other.inputs_.isEmpty()) {
            if (inputsBuilder_.isEmpty()) {
              inputsBuilder_.dispose();
              inputsBuilder_ = null;
              inputs_ = other.inputs_;
              bitField0_ = (bitField0_ & ~0x00000004);
              inputsBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getInputsFieldBuilder() : null;
            } else {
              inputsBuilder_.addAllMessages(other.inputs_);
            }
          }
        }
        if (outputsBuilder_ == null) {
          if (!other.outputs_.isEmpty()) {
            if (outputs_.isEmpty()) {
              outputs_ = other.outputs_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureOutputsIsMutable();
              outputs_.addAll(other.outputs_);
            }
            onChanged();
          }
        } else {
          if (!other.outputs_.isEmpty()) {
            if (outputsBuilder_.isEmpty()) {
              outputsBuilder_.dispose();
              outputsBuilder_ = null;
              outputs_ = other.outputs_;
              bitField0_ = (bitField0_ & ~0x00000008);
              outputsBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getOutputsFieldBuilder() : null;
            } else {
              outputsBuilder_.addAllMessages(other.outputs_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        cn.bubi.protobuf.Privacy.ConfidentialTx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.bubi.protobuf.Privacy.ConfidentialTx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object excessSig_ = "";
      /**
       * <code>optional string excess_sig = 1;</code>
       */
      public java.lang.String getExcessSig() {
        java.lang.Object ref = excessSig_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          excessSig_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string excess_sig = 1;</code>
       */
      public com.google.protobuf.ByteString
      getExcessSigBytes() {
        java.lang.Object ref = excessSig_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          excessSig_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string excess_sig = 1;</code>
       */
      public Builder setExcessSig(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        excessSig_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string excess_sig = 1;</code>
       */
      public Builder clearExcessSig() {

        excessSig_ = getDefaultInstance().getExcessSig();
        onChanged();
        return this;
      }
      /**
       * <code>optional string excess_sig = 1;</code>
       */
      public Builder setExcessSigBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        excessSig_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object excessMsg_ = "";
      /**
       * <code>optional string excess_msg = 2;</code>
       */
      public java.lang.String getExcessMsg() {
        java.lang.Object ref = excessMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          excessMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string excess_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
      getExcessMsgBytes() {
        java.lang.Object ref = excessMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          excessMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string excess_msg = 2;</code>
       */
      public Builder setExcessMsg(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        excessMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string excess_msg = 2;</code>
       */
      public Builder clearExcessMsg() {

        excessMsg_ = getDefaultInstance().getExcessMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string excess_msg = 2;</code>
       */
      public Builder setExcessMsgBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        excessMsg_ = value;
        onChanged();
        return this;
      }

      private java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> inputs_ =
              java.util.Collections.emptyList();
      private void ensureInputsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          inputs_ = new java.util.ArrayList<cn.bubi.protobuf.Privacy.ConfidentialAsset>(inputs_);
          bitField0_ |= 0x00000004;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              cn.bubi.protobuf.Privacy.ConfidentialAsset, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder, cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder> inputsBuilder_;

      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> getInputsList() {
        if (inputsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(inputs_);
        } else {
          return inputsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public int getInputsCount() {
        if (inputsBuilder_ == null) {
          return inputs_.size();
        } else {
          return inputsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset getInputs(int index) {
        if (inputsBuilder_ == null) {
          return inputs_.get(index);
        } else {
          return inputsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder setInputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.set(index, value);
          onChanged();
        } else {
          inputsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder setInputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.set(index, builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder addInputs(cn.bubi.protobuf.Privacy.ConfidentialAsset value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.add(value);
          onChanged();
        } else {
          inputsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder addInputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.add(index, value);
          onChanged();
        } else {
          inputsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder addInputs(
              cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.add(builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder addInputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.add(index, builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder addAllInputs(
              java.lang.Iterable<? extends cn.bubi.protobuf.Privacy.ConfidentialAsset> values) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, inputs_);
          onChanged();
        } else {
          inputsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder clearInputs() {
        if (inputsBuilder_ == null) {
          inputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          inputsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public Builder removeInputs(int index) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.remove(index);
          onChanged();
        } else {
          inputsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder getInputsBuilder(
              int index) {
        return getInputsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder getInputsOrBuilder(
              int index) {
        if (inputsBuilder_ == null) {
          return inputs_.get(index);  } else {
          return inputsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public java.util.List<? extends cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
      getInputsOrBuilderList() {
        if (inputsBuilder_ != null) {
          return inputsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(inputs_);
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder addInputsBuilder() {
        return getInputsFieldBuilder().addBuilder(
                cn.bubi.protobuf.Privacy.ConfidentialAsset.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder addInputsBuilder(
              int index) {
        return getInputsFieldBuilder().addBuilder(
                index, cn.bubi.protobuf.Privacy.ConfidentialAsset.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset inputs = 3;</code>
       */
      public java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder>
      getInputsBuilderList() {
        return getInputsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
              cn.bubi.protobuf.Privacy.ConfidentialAsset, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder, cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
      getInputsFieldBuilder() {
        if (inputsBuilder_ == null) {
          inputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  cn.bubi.protobuf.Privacy.ConfidentialAsset, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder, cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>(
                  inputs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          inputs_ = null;
        }
        return inputsBuilder_;
      }

      private java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> outputs_ =
              java.util.Collections.emptyList();
      private void ensureOutputsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          outputs_ = new java.util.ArrayList<cn.bubi.protobuf.Privacy.ConfidentialAsset>(outputs_);
          bitField0_ |= 0x00000008;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              cn.bubi.protobuf.Privacy.ConfidentialAsset, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder, cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder> outputsBuilder_;

      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset> getOutputsList() {
        if (outputsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(outputs_);
        } else {
          return outputsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public int getOutputsCount() {
        if (outputsBuilder_ == null) {
          return outputs_.size();
        } else {
          return outputsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset getOutputs(int index) {
        if (outputsBuilder_ == null) {
          return outputs_.get(index);
        } else {
          return outputsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder setOutputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.set(index, value);
          onChanged();
        } else {
          outputsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder setOutputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.set(index, builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder addOutputs(cn.bubi.protobuf.Privacy.ConfidentialAsset value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.add(value);
          onChanged();
        } else {
          outputsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder addOutputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset value) {
        if (outputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOutputsIsMutable();
          outputs_.add(index, value);
          onChanged();
        } else {
          outputsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder addOutputs(
              cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.add(builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder addOutputs(
              int index, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder builderForValue) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.add(index, builderForValue.build());
          onChanged();
        } else {
          outputsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder addAllOutputs(
              java.lang.Iterable<? extends cn.bubi.protobuf.Privacy.ConfidentialAsset> values) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, outputs_);
          onChanged();
        } else {
          outputsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder clearOutputs() {
        if (outputsBuilder_ == null) {
          outputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          outputsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public Builder removeOutputs(int index) {
        if (outputsBuilder_ == null) {
          ensureOutputsIsMutable();
          outputs_.remove(index);
          onChanged();
        } else {
          outputsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder getOutputsBuilder(
              int index) {
        return getOutputsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder getOutputsOrBuilder(
              int index) {
        if (outputsBuilder_ == null) {
          return outputs_.get(index);  } else {
          return outputsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public java.util.List<? extends cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
      getOutputsOrBuilderList() {
        if (outputsBuilder_ != null) {
          return outputsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(outputs_);
        }
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder addOutputsBuilder() {
        return getOutputsFieldBuilder().addBuilder(
                cn.bubi.protobuf.Privacy.ConfidentialAsset.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder addOutputsBuilder(
              int index) {
        return getOutputsFieldBuilder().addBuilder(
                index, cn.bubi.protobuf.Privacy.ConfidentialAsset.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.ConfidentialAsset outputs = 4;</code>
       */
      public java.util.List<cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder>
      getOutputsBuilderList() {
        return getOutputsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
              cn.bubi.protobuf.Privacy.ConfidentialAsset, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder, cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>
      getOutputsFieldBuilder() {
        if (outputsBuilder_ == null) {
          outputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  cn.bubi.protobuf.Privacy.ConfidentialAsset, cn.bubi.protobuf.Privacy.ConfidentialAsset.Builder, cn.bubi.protobuf.Privacy.ConfidentialAssetOrBuilder>(
                  outputs_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          outputs_ = null;
        }
        return outputsBuilder_;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protocol.ConfidentialTx)
    }

    // @@protoc_insertion_point(class_scope:protocol.ConfidentialTx)
    private static final cn.bubi.protobuf.Privacy.ConfidentialTx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.bubi.protobuf.Privacy.ConfidentialTx();
    }

    public static cn.bubi.protobuf.Privacy.ConfidentialTx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfidentialTx>
            PARSER = new com.google.protobuf.AbstractParser<ConfidentialTx>() {
      public ConfidentialTx parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfidentialTx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfidentialTx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfidentialTx> getParserForType() {
      return PARSER;
    }

    public cn.bubi.protobuf.Privacy.ConfidentialTx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_protocol_ConfidentialAsset_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_protocol_ConfidentialAsset_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_protocol_ConfidentialTx_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_protocol_ConfidentialTx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\rprivacy.proto\022\010protocol\"|\n\021Confidentia" +
                    "lAsset\022\n\n\002id\030\001 \001(\t\022\016\n\006commit\030\002 \001(\t\022\023\n\013ra" +
                    "nge_proof\030\003 \001(\t\022\025\n\rencrypt_value\030\004 \001(\t\022\023" +
                    "\n\013from_pubkey\030\005 \001(\t\022\n\n\002to\030\006 \001(\t\"\223\001\n\016Conf" +
                    "identialTx\022\022\n\nexcess_sig\030\001 \001(\t\022\022\n\nexcess" +
                    "_msg\030\002 \001(\t\022+\n\006inputs\030\003 \003(\0132\033.protocol.Co" +
                    "nfidentialAsset\022,\n\007outputs\030\004 \003(\0132\033.proto" +
                    "col.ConfidentialAssetB\022\n\020cn.bubi.protobu" +
                    "fb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_protocol_ConfidentialAsset_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ConfidentialAsset_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_protocol_ConfidentialAsset_descriptor,
            new java.lang.String[] { "Id", "Commit", "RangeProof", "EncryptValue", "FromPubkey", "To", });
    internal_static_protocol_ConfidentialTx_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_ConfidentialTx_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_protocol_ConfidentialTx_descriptor,
            new java.lang.String[] { "ExcessSig", "ExcessMsg", "Inputs", "Outputs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}